[tool.briefcase]
project_name = "Just The Tip"
bundle = "com.dmminute"
version = "0.0.1"
url = "https://dmminute.com/JustTheTip"
license = "BSD license"
author = 'Calvin Todd'
author_email = "CSTodd88@gmail.com"

[tool.briefcase.app.JustTheTip]
formal_name = "Just The Tip"
description = "Tip, hourly, paycheck, and tipout tracking application!"
icon = "src/JustTheTip/resources/JustTheTip"
sources = ['src/JustTheTip']
requires = []


[tool.briefcase.app.JustTheTip.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.JustTheTip.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.JustTheTip.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.JustTheTip.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.JustTheTip.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
